# -----------------------------------------------------------------------------
# Bolt v0.4.8
#
# Author: Patrick Hennessy
# Source Code: https://github.com/ns-phennessy/Bolt
# License: MIT
# -----------------------------------------------------------------------------
---

# General
# -----------------------------------------------------------------------------
# Discord API key used to connect to the websocket and use the Discord API
# https://discordapp.com/developers/applications/
api_key: ""

# Bot will refer to itself by this name
# Some plugins may set the bot's name to this
name: "Ms. Pauling"

# Trigger is used as the default prefix for invoking commands
# Some plugins may choose to override this value
trigger: "!"

# Amount of Green threads for the bot to spin up
# These are extremely light threads so high numbers are okay
# This allows for N amount of concurrent work to be performed by the bot
worker_threads: 25

# Database Credentials
# -----------------------------------------------------------------------------
mongo_database_uri: "mongodb://localhost:27017"
mongo_database_username: ""
mongo_database_password: ""
mongo_database_use_tls: false

# Webhook
# -----------------------------------------------------------------------------
webhook_port: 8080

# Plugins
# -----------------------------------------------------------------------------
plugin_dir: /etc/bolt/plugins.enabled.d/

# Logging
# -----------------------------------------------------------------------------
log_level: DEBUG        # Must be one of: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_dir: /var/log/bolt/
