# -----------------------------------------------------------------------------
# Bolt v0.7.9
#
# Author: Patrick Hennessy
# Source Code: https://github.com/ns-phennessy/Bolt
# License: MIT
# -----------------------------------------------------------------------------

# General
# -----------------------------------------------------------------------------
# Discord API key used to connect to the websocket and use the Discord API
# https://discordapp.com/developers/applications/
api_key: ""

# Bot will refer to itself by this name
# Some plugins may set the bot's name to this
name: Bolt

# Trigger is used as the default prefix for invoking commands
# Some plugins may choose to override this value
trigger: "."

# Amount of Green threads for the bot to spin up
# These are extremely light threads so high numbers are okay
# This allows for N amount of concurrent work to be performed by the bot
worker_threads: 5

# Sharding
# -----------------------------------------------------------------------------
# https://discordapp.com/developers/docs/topics/gateway#sharding
shard_total: 1      # Total number of shards to distribute to
shard_id: 0         # Shard number for this node

# Database Credentials
# -----------------------------------------------------------------------------
mongo_database_uri: mongodb://localhost:27017
mongo_database_username: ""
mongo_database_password: ""
mongo_database_use_tls: false

# Webhook
# -----------------------------------------------------------------------------
webhook_enable: false
webhook_port: 8080

# Backdoor Server
# -----------------------------------------------------------------------------
# http://www.gevent.org/api/gevent.backdoor.html
# Backdoor server creates a TCP server you can telnet to a gain access to the
# bot. The server exposes a 'bot' local variable.
backdoor_enable: false
backdoor_host: 127.0.0.1
backdoor_port: 5000

# Plugins
# -----------------------------------------------------------------------------
plugin_dir: /etc/bolt/plugins.enabled.d/
plugin_deps_dir: /etc/bolt/plugins.deps.d/


# Logging
# -----------------------------------------------------------------------------
log_level: INFO        # Must be one of: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_dir: /var/log/bolt/

# Plugin specific
# -----------------------------------------------------------------------------
plugins: {}
